version: "3.8"

services:
  front_app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: front_app
    ports:
      - "50002:81"
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
    networks:
      envoymesh:
networks:
  envoymesh: {}
